[thousandeyes]
homePath   = $SPLUNK_DB/thousandeyes/db
coldPath   = $SPLUNK_DB/thousandeyes/colddb
thawedPath = $SPLUNK_DB/thousandeyes/thaweddb
maxTotalDataSizeMB = 512

[fwa]
homePath   = $SPLUNK_DB/fwa/db
coldPath   = $SPLUNK_DB/fwa/colddb
thawedPath = $SPLUNK_DB/fwa/thaweddb
maxTotalDataSizeMB = 512

[ran]
homePath   = $SPLUNK_DB/ran/db
coldPath   = $SPLUNK_DB/ran/colddb
thawedPath = $SPLUNK_DB/ran/thaweddb
maxTotalDataSizeMB = 512

[twamp]
homePath   = $SPLUNK_DB/twamp/db
coldPath   = $SPLUNK_DB/twamp/colddb
thawedPath = $SPLUNK_DB/twamp/thaweddb
maxTotalDataSizeMB = 512

[telemetry]
homePath   = $SPLUNK_DB/telemetry/db
coldPath   = $SPLUNK_DB/telemetry/colddb
thawedPath = $SPLUNK_DB/telemetry/thaweddb
maxTotalDataSizeMB = 512

[syslog]
homePath   = $SPLUNK_DB/syslog/db
coldPath   = $SPLUNK_DB/syslog/colddb
thawedPath = $SPLUNK_DB/syslog/thaweddb
maxTotalDataSizeMB = 512

[ios]
homePath   = $SPLUNK_DB/ios/db
coldPath   = $SPLUNK_DB/ios/colddb
thawedPath = $SPLUNK_DB/ios/thaweddb
maxTotalDataSizeMB = 512

[alerts]
homePath   = $SPLUNK_DB/alerts/db
coldPath   = $SPLUNK_DB/alerts/colddb
thawedPath = $SPLUNK_DB/alerts/thaweddb
maxTotalDataSizeMB = 512

[episode]
homePath   = $SPLUNK_DB/episode/db
coldPath   = $SPLUNK_DB/episode/colddb
thawedPath = $SPLUNK_DB/episode/thaweddb
maxTotalDataSizeMB = 512

[ai_lab_logs]
homePath   = $SPLUNK_DB/ai_lab_logs/db
coldPath   = $SPLUNK_DB/ai_lab_logs/colddb
thawedPath = $SPLUNK_DB/ai_lab_logs/thaweddb
maxTotalDataSizeMB = 512
