[script://./bin/launcher.py]
interval = -1
sourcetype = ai_lab:launcher
index     = main
disabled  = false

[monitor://$SPLUNK_HOME/etc/apps/ai_lab/var/spool/ai_lab/thousandeyes/cisco_thousandeyes_metric/]
disabled = false
index = thousandeyes
sourcetype = cisco:thousandeyes:metric
host = thousandeyes_at_r9
source = ai_lab:script:thousandeyes_metric
crcSalt = <SOURCE>
whitelist = \.json$
recursive = true

[monitor://$SPLUNK_HOME/etc/apps/ai_lab/var/spool/ai_lab/thousandeyes/cisco_thousandeyes_alerts/]
disabled = false
index = thousandeyes
sourcetype = cisco:thousandeyes:alerts
host = thousandeyes_at_r9
source = ai_lab:script:thousandeyes_alerts
crcSalt = <SOURCE>
whitelist = \.json$
recursive = true

[monitor://$SPLUNK_HOME/etc/apps/ai_lab/var/spool/ai_lab/telemetry/cnc_interface_counter_json/]
disabled = false
index = telemetry
sourcetype = cnc_interface_counter_json
host = router_int_count
source = ai_lab:script:telemetry
crcSalt = <SOURCE>
whitelist = \.json$
recursive = true

[monitor://$SPLUNK_HOME/etc/apps/ai_lab/var/spool/ai_lab/telemetry/cnc_srte_path_json/]
disabled = false
index = telemetry
sourcetype = cnc_srte_path_json
host = cnc_srte_path
source = ai_lab:script:telemetry
crcSalt = <SOURCE>
whitelist = \.txt$
recursive = true

[monitor://$SPLUNK_HOME/etc/apps/ai_lab/var/spool/ai_lab/ai_lab_log/workshop_region/]
disabled = false
index = ai_lab_log
sourcetype = ai_lab:workshop_region:result
host = ai_lab_controller
source = ai_lab:workshop_region:result
crcSalt = <SOURCE>
whitelist = \.json$
recursive = true

[monitor://$SPLUNK_HOME/etc/apps/ai_lab/var/spool/ai_lab/ai_lab_log/log_generation/]
disabled = false
index = ai_lab_log
sourcetype = ai_lab:log_generation:result
host = ai_lab_controller
source = ai_lab:log_generation:result
crcSalt = <SOURCE>
whitelist = \.json$
recursive = true
