[cnc_interface_counter_json]
DATETIME_CONFIG =
INDEXED_EXTRACTIONS = json
KV_MODE = none
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Structured
description = JavaScript Object Notation format. For more information, visit http://json.org/
pulldown_type = 1
TRUNCATE = 50000

[cnc_service_health_json]
DATETIME_CONFIG =
INDEXED_EXTRACTIONS = json
KV_MODE = none
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Structured
description = JavaScript Object Notation format. For more information, visit http://json.org/
pulldown_type = 1

[cnc_srte_path_json]
DATETIME_CONFIG =
INDEXED_EXTRACTIONS = json
KV_MODE = none
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Structured
description = JavaScript Object Notation format. For more information, visit http://json.org/
pulldown_type = 1

[cisco:ios]
EXTRACT-router = (?<router>[^\s]+)\.5gsc\.lab

[cisco:thousandeyes:metric]
SHOULD_LINEMERGE = 0
pulldown_type = 1
DATETIME_CONFIG = CURRENT
KV_MODE = json
TRUNCATE = 999999999
FIELDALIAS-dest = server.address ASNEW dest
FIELDALIAS-target = server.address ASNEW target
FIELDALIAS-dest_port = server.port ASNEW dest_port
FIELDALIAS-error_code = error.type ASNEW error_code
FIELDALIAS-http_method = http.request.method ASNEW http_method
FIELDALIAS-http_status = http.response.status_code ASNEW status
FIELDALIAS-http_thruput = metric_name:http.server.throughput ASNEW thruput
FIELDALIAS-transport = network.transport ASNEW transport
FIELDALIAS-direction = network.io.direction ASNEW direction
FIELDALIAS-query = dns.question.name ASNEW query
FIELDALIAS-duration = metric_name:dns.lookup.duration ASNEW duration
FIELDALIAS-ftp_status = ftp.response.status_code ASNEW status
FIELDALIAS-ftp_thruput = metric_name:ftp.server.throughput ASNEW thruput
FIELDALIAS-sip_status = sip.response.status_code ASNEW status
FIELDALIAS-dvc = thousandeyes.target.agent.id ASNEW dvc
EVAL-response_time = coalesce('metric_name:http.client.request.duration' * 1000, 'metric_name:ftp.client.request.duration' * 1000, 'metric_name:sip.client.request.duration' * 1000, 'metric_name:rtp.client.request.duration' * 1000)
