[set_host_from_cnc_srte_path_json]
REGEX = \"vlan\"\s*:\s*\"([^\"]+)\"
FORMAT = host::$1
DEST_KEY = MetaData:Host

[set_host_from_cnc_service_health_json]
REGEX = \"vlan\"\s*:\s*\"([^\"]+)\"
FORMAT = host::$1
DEST_KEY = MetaData:Host
