# Type stubs for Splunk’s embedded `splunk.Intersplunk` module (editor / Pyright / Pylance only).

def readInput() -> str: ...
def getKeywordsAndOptions() -> object: ...
def getInfo() -> object: ...
def isGetinfo(args: list[str] | None = None) -> bool: ...
def outputResults(
    results: list[object] | None = None, fields: list[str] | None = None
) -> None: ...
def getOrganizedResults() -> object: ...
def getKVPairFromKeywords(keyword_args: str) -> object: ...
